baseURL = "https://videogamemakers.page/"
theme = "hugo-theme-codex"
languageCode = "en-us"
title = "Cultural participation of video game makers"
enableEmoji = true
copyright = "© 2020−2021. Raman Voranau, raman.voranau@mymail.unisa.edu.au"
publishdir = "docs"

[params]
  author = "Raman Voranau"
  description = "I interview video game makers from Australia studying their leisure time."
  favicon = "favicon.ico"
  twitter = "https://twitter.com/ramanvoranau"
  github = "https://github.com/voranau"
  [params.footer]
    text = "By Raman Voranau"
    url = "https://github.com/voranau"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Researcher"
    url = "/researcher"
    weight = 4
  [[menu.main]]
    name = "Team"
    url = "/team"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files